# Main build pipeline, operates on `master` branch which is our integration branch

name: CI Master branch

on:
  push:
    branches: [ "master" ]         # trap each push to master branch
    paths:                         # but react only to changes in code or pipeline definition
      - evita*/**/*.java
      - evita*/**/pom.xml
      - evita*/**/dist/**.*
      - docker/**.*
      - .github/**.*

concurrency:
  group: ${{ github.ref_name }}   # for the same branch
  cancel-in-progress: true        # run only one workflow at a time (cancel the previous)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    # checkout sources

    - name: Setup Java JDK
      uses: actions/setup-java@v3  # setup JDK 17 for building
      with:
         distribution: 'temurin'
         java-version: '17'
         cache: 'maven'
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_CENTRAL_TOKEN
         gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
         gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Build with Maven       # run Maven without tests (tests must pass in dev branch)
      run: mvn -T 1C -B deploy -Dmaven.test.skip=true --file pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Upload evitaDB server artifact   # upload `evita-server.jar` for `docker.yml` to deploy to DockerHub
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: evita-server.jar
        path: 'evita_server/target/evita-server.jar'