name: CI

on:
  push:
    branches: [ "dev" ]
    paths:
      - evita*/**/*.java
      - evita*/**/pom.xml
      - .github/**.*
  pull_request:
    branches: [ "dev" ]
    paths:
      - evita*/**/*.java
      - evita*/**/pom.xml
      - .github/**.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

