name: CI

on:
  push:
    branches: [ "dev" ]
    paths:
      - evita*/**/*.java
      - evita*/**/pom.xml
      - .github/**.*
  pull_request:
    branches: [ "dev" ]
    paths:
      - evita*/**/*.java
      - evita*/**/pom.xml
      - .github/**.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
         distribution: 'temurin'
         java-version: '17'
         cache: 'maven'

    - name: Build with Maven
      run: mvn -B package -P unitAndFunctional jacoco:report-aggregate -V --fail-at-end -Dmaven.test.skip=false --file pom.xml

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-results
        path: 'evita*/**/target/surefire-reports/TEST-*.xml'

    - name: Upload evitaDB server artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: ${{vars.RELEASE_ARTIFACT}}
        path: 'evita_server/target/evita-server.jar'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
