# This workflow generates JUnit report in GitHub from the published test results artifact

name: Test-Report

on:
  workflow_run:
    workflows: ['CI Dev branch', 'All tests including long-running'] # runs after CI of full test workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: JUnit Tests                 # Name of the check run which will be created
          path: '**/*Test.xml'              # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
          fail-on-error: false              # mark this job OK even if there are test failures (original workflow fails)