# This workflow generates JUnit report in GitHub from the published test results artifact

name: Test-Report

on:
  workflow_run:
    workflows: ['CI Dev branch', 'All tests including long-running'] # runs after CI of full test workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          artifact: test-results            # artifact name
          report_paths: '**/TEST-*.xml'